export const REGION_THUMBNAILS: Record<string, string> = {
  'CONUS': '/region-thumbnails/conus.png',
  'Northwest US': '/region-thumbnails/northwest-us.png',
  'Northern Plains': '/region-thumbnails/northern-plains.png',
  'Central Plains': '/region-thumbnails/central-plains.png',
  'Northeast': '/region-thumbnails/northeast.png',
  'Eastern US': '/region-thumbnails/eastern-us.png',
  'Southwest US': '/region-thumbnails/southwest-us.png',
  'South Central': '/region-thumbnails/south-central.png',
  'Southeast US': '/region-thumbnails/southeast-us.png',
  'Western US': '/region-thumbnails/western-us.png',
  'Alaska': '/region-thumbnails/alaska.png',
  'Hawaii': '/region-thumbnails/hawaii.png',
  'North America': '/region-thumbnails/north-america.png',
  'Northern Hemisphere': '/region-thumbnails/northern-hemisphere.png',
  'Southern Hemisphere': '/region-thumbnails/southern-hemisphere.png',
  'North Pacific': '/region-thumbnails/north-pacific.png',
  'Northern Africa': '/region-thumbnails/northern-africa.png',
  'Europe': '/region-thumbnails/europe.png',
  'Asia': '/region-thumbnails/asia.png',
  'Middle East': '/region-thumbnails/middle-east.png',
  'East Asia': '/region-thumbnails/east-asia.png',
  'Australia': '/region-thumbnails/australia.png',
  'Southeast Canada': '/region-thumbnails/southeast-canada.png',
  'Western Canada': '/region-thumbnails/western-canada.png',
  'Canada': '/region-thumbnails/canada.png',
  'South America': '/region-thumbnails/south-america.png',
  'World': '/region-thumbnails/world.png',
  'Indian Ocean': '/region-thumbnails/indian-ocean.png',
  'North Atlantic': '/region-thumbnails/north-atlantic.png',
  'Western Atlantic': '/region-thumbnails/western-atlantic.png',
  'Tropical Atlantic': '/region-thumbnails/tropical-atlantic.png',
  'Western Pacific': '/region-thumbnails/western-pacific.png',
  'Central Pacific': '/region-thumbnails/central-pacific.png',
  'Eastern Pacific': '/region-thumbnails/eastern-pacific.png',
  'Southwest Pacific': '/region-thumbnails/southwest-pacific.png',
  'Southeast Pacific': '/region-thumbnails/southeast-pacific.png',
  'India': '/region-thumbnails/india.png',
  'Southern Africa': '/region-thumbnails/southern-africa.png',
}
