export const REGION_PREVIEWS: Record<string, string> = {
  'CONUS': '/region-previews/conus.png',
  'Northwest US': '/region-previews/northwest-us.png',
  'Northern Plains': '/region-previews/northern-plains.png',
  'Central Plains': '/region-previews/central-plains.png',
  'Northeast': '/region-previews/northeast.png',
  'Eastern US': '/region-previews/eastern-us.png',
  'Southwest US': '/region-previews/southwest-us.png',
  'South Central': '/region-previews/south-central.png',
  'Southeast US': '/region-previews/southeast-us.png',
  'Caribbean': '/region-previews/caribbean.png',
  'Western US': '/region-previews/western-us.png',
  'Alaska': '/region-previews/alaska.png',
  'Hawaii': '/region-previews/hawaii.png',
  'North America': '/region-previews/north-america.png',
  'Northern Hemisphere': '/region-previews/northern-hemisphere.png',
  'Southern Hemisphere': '/region-previews/southern-hemisphere.png',
  'North Pacific': '/region-previews/north-pacific.png',
  'Northern Africa': '/region-previews/northern-africa.png',
  'Europe': '/region-previews/europe.png',
  'Asia': '/region-previews/asia.png',
  'Middle East': '/region-previews/middle-east.png',
  'East Asia': '/region-previews/east-asia.png',
  'Australia': '/region-previews/australia.png',
  'New Zealand': '/region-previews/new-zealand.png',
  'Southeast Canada': '/region-previews/southeast-canada.png',
  'Western Canada': '/region-previews/western-canada.png',
  'Canada': '/region-previews/canada.png',
  'South America': '/region-previews/south-america.png',
  'World': '/region-previews/world.png',
  'Indian Ocean': '/region-previews/indian-ocean.png',
  'North Atlantic': '/region-previews/north-atlantic.png',
  'Western Atlantic': '/region-previews/western-atlantic.png',
  'Tropical Atlantic': '/region-previews/tropical-atlantic.png',
  'Western Pacific': '/region-previews/western-pacific.png',
  'Central Pacific': '/region-previews/central-pacific.png',
  'Eastern Pacific': '/region-previews/eastern-pacific.png',
  'Southwest Pacific': '/region-previews/southwest-pacific.png',
  'Southeast Pacific': '/region-previews/southeast-pacific.png',
  'India': '/region-previews/india.png',
  'Southern Africa': '/region-previews/southern-africa.png',
}
